### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by DrToxic** [mmdanggg2/D3D9DrvRTX#1]
Hello. Using a Steam copy of the game, I have followed the instructions given (Including patching and editing the config), and Unreal Tournament is throwing three errors.

The first as titled, Entry point not found:
The procedure entry point ??0FCoords@@QAE@ABV0@@Z could not be located in the dynamic link library ~\Unreal Tournament\System\D3D9DrvRTX.DLL
![image](https://github.com/mmdanggg2/D3D9DrvRTX/assets/41945324/ccaaa766-7154-4402-8255-ad88468dac8e)

The second is a repeat of the first. These errors seem to only appear when not running the game through Steam.
the third is persistant, running through steam or directly from UnrealTournament.exe:
Critical Error: Can't find file for package 'D3D9DrvRTX'

History: UObject::SafeLoadError <- UObject::staticLoadClass <- UGameEngine:init <- InitEngine
![image](https://github.com/mmdanggg2/D3D9DrvRTX/assets/41945324/0ed93a83-fd58-4993-b6b9-4f8b6d9ce1f5)

UnrealTournament.log, if you're interested:
Log: Log file open, 03/07/24 19:08:41
Init: Name subsystem initialized
Init: Detected: Microsoft Windows NT 6.2 (Build: 9200)
Init: Version: 436
Init: Compiled: Oct 24 2000 23:40:18
Init: Command line: 
Init: Base directory: D:\SteamLibrary\steamapps\common\Unreal Tournament\system\
Init: Character set: Unicode
Log: Bound to Engine.dll
Log: Bound to Core.dll
Log: Bound to Window.dll
Init: Object subsystem initialized
Init: Computer: TOXBOX
Init: User: DrToxic
Init: Memory total: Phys=2097151K Pagef=4194303K Virt=2097024K
Init: Working set: 32000 / 159000
Init: CPU Speed=2495.997772 MHz
Init: CPU Page size=4096, Processors=16
Init: CPU Detected: PentiumPro-class processor (GenuineIntel)
Init: CPU Features: CMov FPU RDTSC PAE MMX KNI
Localization: No localization: Startup.IDDIALOG_WizardDialog.IDC_WizardDialog (int)
Init: Unreal engine initialized
Log: Bound to WinDrv.dll
Init: Mouse info: 6 10 1
Init: Client initialized
Warning: Failed to load 'D3D9DrvRTX': Can't find file for package 'D3D9DrvRTX'
Warning: Failed to load 'Class D3D9DrvRTX.D3D9Render': Can't find file for package 'D3D9DrvRTX'
Warning: Can't find file for package 'D3D9DrvRTX'
Critical: appError called:
Critical: Can't find file for package 'D3D9DrvRTX'
Critical: Windows GetLastError: There are no more files. (18)
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Critical: UObject::SafeLoadError
Critical: UObject::StaticLoadClass
Critical: UGameEngine::Init
Critical: InitEngine
Exit: Exiting.
Uninitialized: Name subsystem shut down
Uninitialized: Log file closed, 03/07/24 19:09:20

I hope we an figure a solution to this.
TIA. DrToxic

**Comment by mmdanggg2** [comment]
Your log says `Init: Version: 436` which suggests that you haven't installed the [OldUnreal patch](https://github.com/OldUnreal/UnrealTournamentPatches/releases) correctly.
