### ISSUE TITLE
Cannot Get Harry Potter Philosopher's Stone to look good

### ISSUE THREAD

**Issue by rytir2001** [mmdanggg2/D3D9DrvRTX#12]
Hi, I don't know if this is the appropriate place to ask my question, but I am trying to run the Harry Potter game, but I seem to not be able to configure it properly. After following all the steps, the game looks the same (extremely pixelated) and sadly opens in a small window instead of in fullscreen.

Please let me know what I need to share in order to get help.

Thank you!

**Comment by rytir2001** [comment]
![image](https://github.com/user-attachments/assets/9faa1db2-27ea-4079-9d3d-7e478be3e35d)

**Comment by mmdanggg2** [comment]
You could try setting the fullscreen resolution to your screen's in the `HP.ini` under the `[WinDrv.WindowsClient]` section

**Comment by rytir2001** [comment]
So uh, I changed the resolution, but now the game UI is ridiculously big

**Comment by rytir2001** [comment]
so I cannot do anything
![image](https://github.com/user-attachments/assets/5efa0fe6-8c06-4e94-a572-9ecff0e08a47)

**Comment by mmdanggg2** [comment]
Oh yea, the game doesn't support widescreen resolutions. You will need to get a widescreen fix mod, there are a few available.

**Comment by rytir2001** [comment]
Could you please link me one?

**Comment by mmdanggg2** [comment]
https://www.pcgamingwiki.com/wiki/Harry_Potter_and_the_Philosopher%27s_Stone#Widescreen_resolution

**Comment by rytir2001** [comment]
Most of the stuff finally works, thanks for your assistance, but the sky seems to be broken... any fix for that?

![image](https://github.com/user-attachments/assets/362420e6-3ed7-4714-8df6-d0e542508de4)

**Comment by mmdanggg2** [comment]
Good to see you got it working!. No fix for the sky yet, still need to figure out how to get skyboxes working with remix in a reasonable manner.

**Comment by rytir2001** [comment]
oh that's unfortunate - I will continue to follow this, I really want to play the game, as it's one of the first games I ever played as a tiny kid. What you have so far is awesome! What is the workflow for this? Is there some kind of editor for remix or something?

**Comment by mmdanggg2** [comment]
Yes, there's RTX Remix Toolkit to help with modding the textures and models to get the game to actually look any good. Plenty of resources on the Remix discord if you need help with that.
