### ISSUE TITLE
Deus Ex - renderer not detected

### ISSUE THREAD

**Issue by DaSk79130569** [mmdanggg2/D3D9DrvRTX#2]
Probably I am stupid but I am using the GOG version of Deus Ex and when I follow the instructions the renderer is simply not an available option?

**Comment by mmdanggg2** [comment]
You don't select the render in the menu, you have to modify the .ini as described in the readme.

**Comment by DaSk79130569** [comment]
I was able to fix the problem. Deus Ex was insisting for me to select a render device on boot, which overwrote the ini change. Thanks.

**Comment by mmdanggg2** [comment]
Latest update should fix it not showing up in the render menu
