### ISSUE TITLE
Unclear on how to fix pink textures

### ISSUE THREAD

**Issue by msimic** [mmdanggg2/D3D9DrvRTX#4]
A lot of map textures and player effects are pink.
I understand that the game generates these in runtime.
Is there a way to fix these?
Can these be downloaded from somewhere or?

The log file on a few maps produces these:

  C:\GAMES\Unreal Tournament\System\UnrealTournament.log (37 hits)
	Line  120: Dev: Generating magic hash texture for 'RainFX.Hfluid2'
	Line  121: Dev: Generating magic hash texture for 'NaliFX.ShaneFx.TORCHES2'
	Line  141: Dev: Generating magic hash texture for 'RainFX.Hfluid2'
	Line  142: Dev: Generating magic hash texture for 'NaliFX.ShaneFx.TORCHES2'
	Line  269: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.bluestuff'
	Line  270: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.Top'
	Line  271: Dev: Generating magic hash texture for 'Botpack.ShaneFx.top3'
	Line  272: Dev: Generating magic hash texture for 'hubeffects.Goop3'
	Line  273: Dev: Generating magic hash texture for 'SpaceFX.worm3b'
	Line  276: Dev: Generating magic hash texture for 'Botpack.Ammocount.AmmoLed'
	Line  277: Dev: Generating magic hash texture for 'Botpack.Ammocount.miniammoled'
	Line  385: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.bluestuff'
	Line  386: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.Top'
	Line  387: Dev: Generating magic hash texture for 'Botpack.ShaneFx.top3'
	Line  388: Dev: Generating magic hash texture for 'hubeffects.Goop3'
	Line  389: Dev: Generating magic hash texture for 'SpaceFX.worm3b'
	Line  397: Dev: Generating magic hash texture for 'Botpack.Ammocount.miniammoled'
	Line  398: Dev: Generating magic hash texture for 'UnrealShare.Belt_fx.ShieldBelt.N_Shield'
	Line  399: Dev: Generating magic hash texture for 'UnrealShare.Belt_fx.UDamageFX'
	Line  400: Dev: Generating magic hash texture for 'Botpack.Ammocount.AmmoLed'
	Line  497: Dev: Generating magic hash texture for 'hubeffects.LavaBEF'
	Line  498: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.bluestuff'
	Line  499: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.Top'
	Line  500: Dev: Generating magic hash texture for 'Botpack.ShaneFx.top3'
	Line  501: Dev: Generating magic hash texture for 'UnrealShare.Belt_fx.Invis.Invis'
	Line  502: Dev: Generating magic hash texture for 'Liquids.liquid9'
	Line  510: Dev: Generating magic hash texture for 'UnrealShare.Effect56.fireeffect56'
	Line  511: Dev: Generating magic hash texture for 'UnrealShare.Belt_fx.ShieldBelt.N_Shield'
	Line  512: Dev: Generating magic hash texture for 'Botpack.Ammocount.FlakAmmoLED'
	Line  513: Dev: Generating magic hash texture for 'Botpack.Ammocount.miniammoled'
	Line  642: Dev: Generating magic hash texture for 'Botpack.ShaneFx.top3'
	Line  650: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.bluestuff'
	Line  651: Dev: Generating magic hash texture for 'Botpack.ShaneFx.Health.Top'
	Line  652: Dev: Generating magic hash texture for 'Botpack.Ammocount.FlakAmmoLED'
	Line  653: Dev: Generating magic hash texture for 'UnrealShare.Belt_fx.ShieldBelt.N_Shield'
	Line  654: Dev: Generating magic hash texture for 'Botpack.Ammocount.miniammoled'
	Line  655: Dev: Generating magic hash texture for 'UnrealShare.Belt_fx.UDamageFX'

**Comment by msimic** [comment]
> Did you read [the readme](https://github.com/mmdanggg2/D3D9DrvRTX?tab=readme-ov-file#hash-textures-help-some-textures-are-pink-mush)?

Ah so we dont need them at all, so if any such texture comes in the log we can put it there?
If that is so fine, but then the blacklist file can be the same for all users and could be put on github?

**Comment by mmdanggg2** [comment]
Well if you're not going to start replacing those textures with remix and you just want to play it as is then you can just turn the hash textures off in the ini file as described.

**Comment by msimic** [comment]
Ah I misunderstood the scope of this project then.
I tought this was a rtx remix mod for UT.
I understand now. This is only a renderer that supports it.
It explains also that materials dont seem to be changed (no reflectivity etc).
Do you know if there is some actual mod already for download that does the remix tweaks?

**Comment by mmdanggg2** [comment]
There is at least one I know of in the works but not released yet for UT99, but yes this project is only the renderer that enables remix to work with the games.
