### ISSUE TITLE
ACE?

### ISSUE THREAD

**Issue by coroner71** [mmdanggg2/D3D9DrvRTX#6]
ACEv12 screens this DLL, anyone open a review of it yet? (D3D9DrvRTX.DLL)

**Comment by mmdanggg2** [comment]
I was not planning to put this to get cleared by the ACE developers. I would also be extremely surprised if it passed since I'm sure it could be used to make wallhacks and such.

**Comment by coroner71** [comment]
Good point - thanks for responding
